module.exports = chatStates = {
    INITIAL_CONVERSATION: "INITIAL_CONVERSATION",
    AWAITING_QUESTION: "AWAITING_QUESTION",
    QUESTION_ANSWERED: "QUESTION_ANSWERED",
    EXPERT_REQUESTED: "EXPERT_REQUESTED",
    EXPERT_CONNECTED: "EXPERT_CONNECTED",
    EXPERT_WAITING: "EXPERT_WAITING",
    FINISHED_CONVERSATION: "FINISHED_CONVERSATION",
}
